/// Represents a single available subtitle/caption track for a video.
class SubtitleOption {
  final String language;
  final String name;
  final String ext;
  final String? url;
  final bool autoGenerated;

  const SubtitleOption({
    required this.language,
    required this.name,
    this.ext = 'vtt',
    this.url,
    this.autoGenerated = false,
  });

  factory SubtitleOption.fromJson(Map<String, dynamic> json) {
    return SubtitleOption(
      language: json['language'] as String,
      name: json['name'] as String,
      ext: json['ext'] as String? ?? 'vtt',
      url: json['url'] as String?,
      autoGenerated: json['auto_generated'] as bool? ?? false,
    );
  }

  /// Human-readable label for display in the UI.
  String get displayLabel {
    final autoTag = autoGenerated ? ' (Auto)' : '';
    return '$name$autoTag';
  }

  /// Short language code for display.
  String get languageCode => language.toUpperCase();
}

/// Result from the /subtitles endpoint.
class SubtitlesResult {
  final List<SubtitleOption> subtitles;
  final List<String> availableLanguages;
  final int count;

  const SubtitlesResult({
    required this.subtitles,
    required this.availableLanguages,
    required this.count,
  });

  factory SubtitlesResult.fromJson(Map<String, dynamic> json) {
    return SubtitlesResult(
      subtitles: (json['subtitles'] as List)
          .map((s) => SubtitleOption.fromJson(s as Map<String, dynamic>))
          .toList(),
      availableLanguages:
          (json['available_languages'] as List).cast<String>(),
      count: json['count'] as int,
    );
  }

  /// Get unique subtitle options (one per language, preferring manual over auto).
  List<SubtitleOption> get uniqueByLanguage {
    final seen = <String>{};
    final result = <SubtitleOption>[];

    // Manual subtitles first
    for (final s in subtitles.where((s) => !s.autoGenerated)) {
      if (!seen.contains(s.language)) {
        seen.add(s.language);
        result.add(s);
      }
    }
    // Then auto-generated
    for (final s in subtitles.where((s) => s.autoGenerated)) {
      if (!seen.contains(s.language)) {
        seen.add(s.language);
        result.add(s);
      }
    }
    return result;
  }
}

/// Supported subtitle download formats.
enum SubtitleFormat {
  srt,
  vtt,
  ass;

  String get extension => name;
  String get displayName => name.toUpperCase();
}

/// Subtitle preference for download: embed in video or save as sidecar file.
enum SubtitleMode {
  embed,
  sidecar;

  String get displayName =>
      this == SubtitleMode.embed ? 'Embed in video' : 'Separate file';
}
